In [3]:
import numpy as np
a=np.array([2,3,4])
b=np.array([5,6,7])
print(a+2)
print(a+b)

[4 5 6]
[ 7  9 11]


In [4]:
print(a*2)

[4 6 8]


In [5]:
print(a**2)

[ 4  9 16]


In [8]:
a=np.array([2,3,4])
b=np.array([5,6,7])
d=((a-b)**2).sum()  #distance between coordinates to find distance
np.sqrt(d)


5.196152422706632

In [10]:
a=np.array([[2,3],[4,5]])
b=np.array([[3,4],[5,6]])
a.dot(b)

array([[21, 26],
       [37, 46]])

In [16]:
a=np.matrix('2 3 4;4 5 6')
# a.shape()