In [1]:
import numpy as np

In [3]:
x= np.array([[1,-1,2]
            ,[2,0,0],
            [0,1,-1]])


In [4]:
from sklearn import preprocessing

In [5]:
x_scaled=preprocessing.scale(x)

In [7]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [8]:
x_scaled.std(axis=0)

array([1., 1., 1.])

In [13]:
scalar = preprocessing.StandardScaler()
scalar.fit(x)
scalar.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [14]:
x_test=[[1,-1,0]]

In [17]:
scalar.transform(x_test)

array([[ 0.        , -1.22474487, -0.26726124]])

In [ ]:
 sk