In [1]:
import math as m
m.sqrt(9)

3.0

In [2]:
import numpy as np

In [3]:
l=[1,2,3]
np.array(l)

array([1, 2, 3])

In [5]:
l=[1,2,3,"sourav"]
np.array(l) #makes every element as string

array(['1', '2', '3', 'sourav'], dtype='<U11')

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
a=np.ones(10,int)
a[0]="0"  #automatically converts into int 
# a[1]="sk"  #this is problem can't convert
# a.dtype 
print(a[2:6])
a.shape  #gives us the size


[1 1 1 1]


(10,)

In [17]:
#multidimensional array
np.zeros((2,3)) #2d arrays
np.zeros((3,4,5)) #3d arrays

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [33]:
a= np.array([[1,2,3],[4,5,6],[12,12,12],[23,23,23]])
a[0]  #gives us the first row

array([1, 2, 3])

In [34]:
a[:,0] #every row and 0th column

array([ 1,  4, 12, 23])

In [36]:
a[0:2,0] #from 0 to 1 row and 0th column

array([1, 4])

In [40]:
a[:,1:3]  #form 1 to 2 column and all row

array([[ 2,  3],
       [ 5,  6],
       [12, 12],
       [23, 23]])